### ISSUE TITLE
Formula Mistake in Paper?

### ISSUE THREAD

**Issue by hu-po** [deeplearning-wisc/vos#1]
Potential formula mistake in the paper? 
![image](https://user-images.githubusercontent.com/8493427/153011247-92c686c7-bceb-49b3-a403-d1c596e007de.png)

**Comment by d12306** [comment]
thanks for the suggestion! will fix!

**Comment by YixuanLi** [comment]
Note that p_\theta(**y**|**x**) produces a vector **y** (for all bounding boxes). Alternatively, p_\theta(y |**x,b**) is also valid conditioned on the box.
