### ISSUE TITLE
Results about OpenImages

### ISSUE THREAD

**Issue by AmingWu** [deeplearning-wisc/vos#10]
Dear Authors,

Could you tell me how the obtain the evaluation results of OpenImages?

**Comment by d12306** [comment]
@AmingWu , hi, you can set the "--test_dataset" to "openimages_ood_val", which is defined https://github.com/deeplearning-wisc/vos/blob/3644d9de4f1613e11cf37723c563b9bcb57ded33/detection/core/datasets/setup_datasets.py#L103.

feel free to reopen the issue if you have further questions!
