### ISSUE TITLE
Test About OpenImages

### ISSUE THREAD

**Issue by AmingWu** [deeplearning-wisc/vos#11]
Dear Authors,

I have trained the model based on BDD. And I have evaluated the model on the COCO successfully. Now I use the same model to evaluate openimages. There is an error.
![QQ截图20220301103543](https://user-images.githubusercontent.com/38445175/156093807-2e6eb7cf-69df-44bf-93dd-ca3be07f7e1a.png)

**Comment by AmingWu** [comment]
The command is:
CUDA_VISIBLE_DEVICES=4 python apply_net.py --dataset-dir /data1/user/vos/OpenImages --test-dataset openimages_ood_val --config-file BDD-Detection/faster-rcnn/vos.yaml --inference-config Inference/standard_nms.yaml --random-seed 0 --image-corruption-level 0 --visualize 0

**Comment by d12306** [comment]
hi, @AmingWu , the evaluation on openimages is not supported in the original version, i have updated the code, can you try again? 
thanks for catching the bug!

**Comment by AmingWu** [comment]
There is an error. I only update evaluation_utils.py and keep other files unchanged
![QQ截图20220301124444](https://user-images.githubusercontent.com/38445175/156106441-3217171a-fa54-4081-8748-4dc0d589c3dd.png)
.

**Comment by AmingWu** [comment]
For the two files in OpenImages, i.e., coco_classes and ood_classes_rm_overlap, they all contain the file COCO-Format, could you give the accurate command about the evaluation on OpenImages? This is an another error:
![QQ截图20220301130419](https://user-images.githubusercontent.com/38445175/156108309-1477e543-c0ce-4f8d-a57c-4625a53b5e46.png)

**Comment by d12306** [comment]
@AmingWu , you can set the --dataset-dir to "/data1/user/vos/OpenImages/" rather than the "/data1/user/vos/OpenImages" or "/data1/user/vos/OpenImages/ood_classes_rm_overlap"

**Comment by d12306** [comment]
let me know if you encounter further questions!

**Comment by AmingWu** [comment]
I have changed the dir as  "/data1/user/vos/OpenImages/". But I still meet the same error.
![QQ截图20220302083507](https://user-images.githubusercontent.com/38445175/156272270-1a2f2752-32ed-4e52-91e1-2f102f38fc85.png)

**Comment by d12306** [comment]
now it should be fine, I updated the repo again.

**Comment by AmingWu** [comment]
Yes, the second step works. However, How to perform the last step to obtain the results of FPR95 and AUROC for OpenImages?

**Comment by AmingWu** [comment]
The current project may lose the file, i.e., bdd_openimages_plot.py and voc_openimages_plot.py.

**Comment by d12306** [comment]
can you please make these files yourself, I think it is very easy and you just change the folder name, right?

**Comment by d12306** [comment]
btw, thanks for catching these bugs on evaluation for OpenImages. Very cool! Thank you so much!

**Comment by AmingWu** [comment]
Thank you. I have solved this problem.
