### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by jorism1993** [deeplearning-wisc/vos#13]
Hi, 

Could you provide a script that can be used for inference? Suppose I have a single image for which I want to know if it is _in distribution_ or _out of distribution_. How can I use your codes to analyze this? Could you point me in the right direction or provide a script for this?

Edit: I am applying for method for a classification task, but a script that works for detection would work too!

**Comment by d12306** [comment]
hi, @jorism1993 , you can calculate the score threshold when the true positive rate of ID samples is at 95%.
In the implementation level, the score threshold can be obtained by "thres = thresholds[cutoff]" below this line.

https://github.com/deeplearning-wisc/vos/blob/7126ea0b2c777f1ddab1710032b244902ee4c360/classification/utils/display_results.py#L64

A similar calculation is also compatible with detection networks.

**Comment by jorism1993** [comment]
Hi,

From where would you recommend calling this function? From `test.py`?

**Comment by d12306** [comment]
yes , @jorism1993
