### ISSUE TITLE
NameError: name 'GaussianNoise' is not defined

### ISSUE THREAD

**Issue by FlyCarrot** [deeplearning-wisc/vos#15]
I think this Function definition is missing, can you fix this?

vos/detection/modeling/roihead_gmm.py", line 540, in __init__
    self.noise = GaussianNoise(sigma=1)

**Comment by FlyCarrot** [comment]
I found this definition in the previous version of this file.

class GaussianNoise(nn.Module):
    '''Gaussian noise regularizer.
    Args:
        sigma (float, optional): relative standard deviation used to generate the
            noise. Relative means that it will be multiplied by the magnitude of
            the value your are adding the noise to. This means that sigma can be
            the same regardless of the scale of the vector.
        is_relative_detach (bool, optional): whether to detach the variable before
            computing the scale of the noise. If `False` then the scale of the noise
            won't be seen as a constant but something to optimize: this will bias the
            network to generate vectors with smaller values.
    '''
    def __init__(self, sigma=0.1, is_relative_detach=True):
        super().__init__()
        self.sigma = sigma
        self.is_relative_detach = is_relative_detach
        self.register_buffer('noise', torch.tensor(0))

    def forward(self, x):
        if self.training and self.sigma != 0:
            scale = self.sigma * x.detach() if self.is_relative_detach else self.sigma * x
            sampled_noise = self.noise.expand(*x.size()).float().normal_() * scale
            x = x + sampled_noise
        return x

**Comment by d12306** [comment]
@FlyCarrot , yes, this is due to the careless deletion. will fix! thanks!
