### ISSUE TITLE
Missing run.sh inside classification folder. Thanks.

### ISSUE THREAD

**Issue by manoja328** [deeplearning-wisc/vos#18]
Testing and Fine-tuning
run energy score testing for cifar10 WRN

bash run.sh energy 0
run energy score testing for cifar100 WRN

bash run.sh energy 1
run energy score training and testing for cifar10 WRN

**Comment by d12306** [comment]
@manoja328 , thanks for the suggestions! we have provided the necessary command lines in the readme file so the bash file is not used currently.
