### ISSUE TITLE
Preparing classification datasets

### ISSUE THREAD

**Issue by SUPER-TADORY** [deeplearning-wisc/vos#19]
Dear Author, 

I'm trying to run your code and I have a trouble with preparing classification datasets. (places365, iSUN, LSUN-C, LSUN-Resize)
I downloaded these datasets but there are only images in the folder. There are no class labels.
Would you tell me where I can download classification datasets with class labels?  Thank you.

**Comment by d12306** [comment]
@SUPER-TADORY , please follow this repo https://github.com/wetliu/energy_ood for dataset preparation!

**Comment by yusukefukuju** [comment]
Thank you, @d12306!
Which dataset split did you use for evaluation on LSUN-C?
I could not find the label in the test dataset split in https://www.dropbox.com/s/fhtsw1m3qxlwj6h/LSUN.tar.gz

**Comment by yusukefukuju** [comment]
The same problem in iSUN, LSUN-Resize ...

**Comment by d12306** [comment]
![image](https://user-images.githubusercontent.com/42554178/159828666-a5181615-80d5-4022-bd03-a249749ed563.png)
can you please download the datasets using the link here? You do not need any test labels or splits.

**Comment by d12306** [comment]
@kondounagi @SUPER-TADORY
