### ISSUE TITLE
About evaluation outputs

### ISSUE THREAD

**Issue by misraya** [deeplearning-wisc/vos#21]
Hi,

First of all, great project! Thanks for making the code public. 

I was checking the evaluation when ID is BDD and couldn't understand how to interpret the outputs I share below. Can you elaborate on these?

+------------------+---------------------+---------------------+-----------------------------+---------------------+
|   Output Type    | Number of Instances | Cls Ignorance Score | Cls Brier/Probability Score | Reg Ignorance Score |
+------------------+---------------------+---------------------+-----------------------------+---------------------+
| False Positives: |        205497       |        3.6216       |            1.4465           |       -3.5162       |
+------------------+---------------------+---------------------+-----------------------------+---------------------+

Also, not very crucial, but in the **Evaluation with the in-distribution dataset to be BDD** part of the README file, you still use VOC-Detection in the config file arg, which should be BDD-Detection. And requirements.txt is missing a few packages such as ujson, prettytable, and uncertainty-calibration.

**Comment by d12306** [comment]
hi, @misraya , thanks for the interest in our project. these outputs are useless because we write the code based on the https://github.com/asharakeh/probdet, their code outputs these values.

For the errors in readme file, thanks for the suggestions, will fix.

**Comment by misraya** [comment]
Alright, thank you.
