### ISSUE TITLE
RuntimeError: cholesky_cuda: U(1, 1) is zero, singular U.

### ISSUE THREAD

**Issue by hantaotao** [deeplearning-wisc/vos#22]
Hello, I'm very interested in your work. I encountered the following errors when training on my own training set. How should I solve them? thank you!
RuntimeError: cholesky_cuda: U(1, 1) is zero, singular U.

**Comment by d12306** [comment]
hi, @hantaotao , thanks for the interest in our paper. you can refer to this issue. https://github.com/deeplearning-wisc/vos/issues/7
