### ISSUE TITLE
Can this method of vos be used in the yolo model?

### ISSUE THREAD

**Issue by konioy** [deeplearning-wisc/vos#23]
I want to use this method in yolo, but during the implementation process, I encountered some problems. Has anyone used this method in yolo? Or have any suggestions?

**Comment by konioy** [comment]
@d12306 @Venseven

**Comment by d12306** [comment]
@konioy ， thanks for your interest! I think the virtual outlier sampling is still feasible in yolo. basically, you maintain a class-conditional queue and sample from the low-density space. But the most advanced yolo seems to use the binary-sigmoid-focal loss for training. It is not multi-class classification yet. Thus, i am not sure whether you can use the energy-score for training again. But you can try to implement it and see the result.

**Comment by konioy** [comment]
Thanks for your answer! 
In Faster RCNN, the features of all anchors are used to generate OOD samples. But in yolo, there seems to be no anchor features, only features for each grid, so I don't know what to generate the OOD samples based on. Or I misunderstood, please advise.

**Comment by d12306** [comment]
@konioy , during the calculation of the focal loss, there are grids that are assigned as the gt labels, you can use such features to build the queue. once you have the queue, you can model each id class as a class-conditional gaussian, then sample from it, which is the same as vos.

**Comment by MoaazAbdulrahman** [comment]
Hi @konioy,

I am interested in what you are doing with yolo. Are you able to get any results?

**Comment by konioy** [comment]
I simply implemented it and found that the training speed was 3 times slower, so I put it on hold.
