### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by wonjeongchoi** [deeplearning-wisc/vos#24]
Hi
First of all, I really appreciate your great work.

I have one question about the paper, **the Section 3.2. Unknown-Aware Training Objective - Uncertainty regularization for classification.**
In that section, you note that the log partition function E(x; \theta) is proportional to log p(x) with some unknown factor,  which can be seen from the following:

![render](https://user-images.githubusercontent.com/80087614/163533344-0c5f1325-6889-4833-b49a-df550e144859.png)

From the above equation, how can we know the log partition function is proportional to log p(x)?

Thank you.

**Comment by Dwrety** [comment]
simply take the log of both sides and work out the math, you should be able to see they are proportional.
