### ISSUE TITLE
Question abuout evaluation

### ISSUE THREAD

**Issue by AceCoooool** [deeplearning-wisc/vos#28]
Before evaluation FPR95 and AUROC, the predictions are filtered by "a threshold", why after this filter, the left predictions can be seen as "in-distribution object?", and what's meaning about this optimal_score_threshold. thank you~
```
    # Compute optimal micro F1 score threshold. We compute the f1 score for
    # every class and score threshold. We then compute the score threshold that
    # maximizes the F-1 score of every class. The final score threshold is the average
    # over all classes.
    precisions = results_api.eval['precision'].mean(0)[:, :, 0, 2]
    recalls = np.expand_dims(results_api.params.recThrs, 1)
    f1_scores = 2 * (precisions * recalls) / (precisions + recalls)
    optimal_f1_score = f1_scores.argmax(0)
    scores = results_api.eval['scores'].mean(0)[:, :, 0, 2]
    optimal_score_threshold = [scores[optimal_f1_score_i, i]
                               for i, optimal_f1_score_i in enumerate(optimal_f1_score)]
    optimal_score_threshold = np.array(optimal_score_threshold)
    optimal_score_threshold = optimal_score_threshold[optimal_score_threshold != 0]
    optimal_score_threshold = optimal_score_threshold.mean()
```

**Comment by AceCoooool** [comment]
1. the predictions with confidence larger than `optimal_score_threshold` can not be guaranteed to be TP?  (For examples: the blue is the tp in the voc test data, the green is the fp in the voc test data; both of them are the predictions from vos pre-trained model)
![1](https://user-images.githubusercontent.com/16620320/167131424-707adab3-ef4b-4ed8-859f-cabcfe1a16bf.png) ![2](https://user-images.githubusercontent.com/16620320/167131457-56aa7b88-a48e-4050-94b3-e5c4dbaa2a80.png)

2. why use the mean of optimal-score-threshold rather than a list of threshold?

**Comment by d12306** [comment]
hi, @AceCoooool , i think the threshold is for filtering the predictions with low confidence. not on the energy score. we follow the paper https://openreview.net/pdf?id=YLewtnvKgR7.

why after this filter, the left predictions can be seen as "in-distribution object?",
--we did not regard the remaining objects after filtering as the in-distribution object. The filtering threshold is the same for both the id and ood data.

**Comment by d12306** [comment]
the predictions with confidence larger than optimal_score_threshold can not be guaranteed to be TP? 

--this is definitely true, otherwise, the mAP will be very large (100%) for the object detection models, right? because precision = tp/(tp+fp)

**Comment by AceCoooool** [comment]
> --this is definitely true, otherwise, the mAP will be very large (100%) for the object detection models, right? because precision = tp/(tp+fp)

Thank you for you help ! 
Using the pretrained model in VOC, we can get the following results. 
VOS: optimal_score_threshold=0.5831 => after filter: TP=11682, FP=4635, there are nearly 30% FP in id data
Vanilla: optimal_score_threshold=0.5686 => after filter: TP=11684, FP=4460, there are nearly 30% FP in id data

1. Does optimal_score_threshold can guarantee the similar number of predictions in both VOS and Vanilla ?
2. Direct set the predictions after filter as in-distribution object may not reasonable? (there are nearly 30% FP), I will read the paper https://openreview.net/pdf?id=YLewtnvKgR7 soon.

Thank you !

**Comment by d12306** [comment]
@AceCoooool , 
Does optimal_score_threshold can guarantee a similar number of predictions in both VOS and Vanilla ?
---as you showed, the number of objects should be similar for both models. You can always verify that whether using the same number of ID and OOD objects (by subsampling) will create different performance. I think VOS will also be better in such cases.

Direct set the predictions after filter as in-distribution object may not reasonable? (there are nearly 30% FP), 
---well, I want to emphasize that we did not regard the remaining objects after filtering as the in-distribution object. The filtering threshold is the same for both the id and ood data. You can also verify the performance of vos by removing the threshold and using different thresholds. Under the same thresholding mechanism, the vos should be the better model.
