### ISSUE TITLE
Calculating the OOD score using VOS in the classification task

### ISSUE THREAD

**Issue by ah-ansari** [deeplearning-wisc/vos#30]
Hello,

How can I calculate the OOD score on the classification models?
I see the "get_ood_scores" function in "vos-main/classification/CIFAR/test.py". Does this function calculate the OOD score for VOS? (or this function only relates to the baselines considered in the paper?).

**Comment by d12306** [comment]
hi, @ah-ansari , thanks for the interest, yes, the file actually calcuates the energy score, which is used in evaluating vos. Using the logistic score and the energy score are equivalent. please see this thread. https://github.com/deeplearning-wisc/vos/issues/20 and https://github.com/deeplearning-wisc/vos/issues/14

**Comment by ah-ansari** [comment]
Many thanks for your response!
It's great that you take time to answer the questions.

**Comment by hyunjunChhoi** [comment]
However, in the paper , the classification models does not use the learnarble weight for energy . Only the detection model use the learnable energy  weight. But in code, both the classification model and the detection model learn the energy weight. In the inference for the classification, they don't load the energy weight. Isn't it the mistake ?? Can you give me the answer??
Thanks in advance
