### ISSUE TITLE
Additional information for Table 4

### ISSUE THREAD

**Issue by danielkorth** [deeplearning-wisc/vos#32]
Hey,

regarding Table 4 in your paper. Is it possible for you to share how VOS performed on the different datasets and not only share the average across them? I trained your model locally and would like to validate that I have not done anything wrong during the training process. Because my FPR95 on SVHN is significanly larger than your reported average value (with DenseNet).

Thank you in advance!

**Comment by d12306** [comment]
Hi, @danielkorth , you cannot compare the average results with a single result on svhn. For the reported result on svhn, please follow the instructions in the readme file and load the model with the provided pretrained models.
