### ISSUE TITLE
path for pre-trained models

### ISSUE THREAD

**Issue by IanGuangleiZhu** [deeplearning-wisc/vos#33]
Sorry if this is a stupid question, but where should I put pre-trained models during evaluation? Also how much memory does it appriximately take for evaluation? Thank you in advance!

**Comment by d12306** [comment]
hi, @IanGuangleiZhu , sorry for late reply. the checkpoint should be placed in ./detection/data/VOC-Detection/faster-rcnn/vos/random_seed_0/

**Comment by d12306** [comment]
feel free to change it here, https://github.com/deeplearning-wisc/vos/blob/25eec0dd1af06bcabccc4b20e8f338bf5de909bb/detection/core/setup.py#L209. the training time for voc dataset takes around 4 hours on 4 2080Tis.
