### ISSUE TITLE
Questions about visualization of inference results

### ISSUE THREAD

**Issue by hori-13** [deeplearning-wisc/vos#34]
Thanks for sharing the very interesting code.

I have a question about visualization of OOD labels.
Learning using the PASCAL VOC dataset was performed with the following command.

python train_net_gmm.py --dataset-dir ../VOC_DATASET_ROOT/ --num-gpus 1 --config-file VOC-Detection/faster-rcnn/vos.yaml --random-seed 0 --resume

Next, I will evaluate the ID data and OOD data.
Inference is done with these codes.

<OOD test>
python apply_net.py --dataset-dir ../COCO_DATASET_ROOT/ --test-dataset coco_ood_val --config-file VOC-Detection/faster-rcnn/vos.yaml --inference-config Inference/standard_nms.yaml --random-seed 0 --image-corruption-level 0 --visualize 1

At this time, if the argument "visualize" is set to "1", the inferred labeled image will be output.
However, when I test the OOD data, the OOD label is not given.
Do I need to change any code thresholds? Or is the argument setting at runtime different?

thank you.

**Comment by d12306** [comment]
hi, @hori-13 , sorry for the late reply. you need to change threshold here https://github.com/deeplearning-wisc/vos/blob/25eec0dd1af06bcabccc4b20e8f338bf5de909bb/detection/apply_net.py#L97. 8.868 is for bdd100k dataset with the ood to be coco.

for the question of how to obtain the threshold, please refer to https://github.com/deeplearning-wisc/vos/issues/13

**Comment by hori-13** [comment]
Thanks for your reply.

In "detection" when the dataset is "PASCAL VOC", I interpreted it to obtain the threshold value as follows.
When "thres = thresholds [cutoff]" is written after "cutoff = np.argmin(np.abs(recall - recall_level))" on line 84 of "vos/metric_utils.py", "thres" is becomes the threshold.
At this time, thres=13.018.
This value was written on line 97 of "vos/detection/apply_net.py".
However, OOD labels were not visualized in the PASCAL VOC dataset.
In a similar way, when I try to get the threshold for the BDD dataset, I get 8.860468, which is close to the threshold set by the author. OOD labels are visualized in the BDD dataset.

#13 explains the method for image classification, and in the case of object detection, I understand that the threshold value is obtained with "metric_utils.py".
Is this understanding correct?

Sorry to trouble you, but I would appreciate it if you could tell me in detail.
