### ISSUE TITLE
How to perform sampling from the feature representation space

### ISSUE THREAD

**Issue by jyang68sh** [deeplearning-wisc/vos#35]
Hi Thanks for your great work!

I am curious on this minor section in the paper. "sampling from the feature representation space". 

Is this coded in the repository? I didnt find a specific piece of code demonstrating the idea.

Thanks!

**Comment by d12306** [comment]
hi, @jyang68sh , please see https://github.com/deeplearning-wisc/vos/blob/25eec0dd1af06bcabccc4b20e8f338bf5de909bb/detection/modeling/roihead_gmm.py#L843.

**Comment by jyang68sh** [comment]
@d12306 Hi I am a little bit confused at the mathematical meaning of the results after this rsample. 

What should I expect to observe if I perform this sampling?
