### ISSUE TITLE
Find it stucks in 12000 iter when trained vos on VOC

### ISSUE THREAD

**Issue by Zigars** [deeplearning-wisc/vos#36]
Using main-MLP branch, and training command：

`python train_net_gmm.py --dataset-dir /data/haitaozhang/dataset/object_detection/VOC --num-gpus 4 --config-file VOC-Detection/faster-rcnn/vos.yaml --random-seed 0 --resume`

![image](https://user-images.githubusercontent.com/32835472/183597082-6e0cb3ff-468e-4544-ac7b-0eca9c506c45.png)

it's stucking in 12000 iter, and gpus usage do not work.
![image](https://user-images.githubusercontent.com/32835472/183597833-52b03fc2-c832-405b-9696-e28a3f7522e8.png)

how can I solve this problem, maybe need use the main branch?

**Comment by Zigars** [comment]
I switch to main branch, and this problem review again, also I change the backbone to regnetx, it doesn't work either, train step was still stucking in 12000 iter, which the default starting vos iter.

**Comment by d12306** [comment]
hi, @Zigars , thanks for the interest in our codebase. not sure about your machine, i think the speed of vos will be slower than the vanilla training, but it will not stuck. 

could you double check whether it is caused by the slower training speed?

**Comment by d12306** [comment]
@Zigars , hi! do you figure out this issue? i actually encountered the same question when I try to reproduce my results. is it related to the version of detectron2 and torch, or cuda version?

**Comment by d12306** [comment]
never mind, i found that we need to use torch 1.7.1 will work.
