### ISSUE TITLE
This question is related to #34

### ISSUE THREAD

**Issue by hori-13** [deeplearning-wisc/vos#37]
In "detection" when the dataset is "PASCAL VOC", I interpreted it to obtain the threshold value as follows.
When "thres = thresholds [cutoff]" is written after "cutoff = np.argmin(np.abs(recall - recall_level))" on line 84 of "vos/metric_utils.py", "thres" is becomes the threshold.
At this time, thres=13.018.
This value was written on line 97 of "vos/detection/apply_net.py".
However, OOD labels were not visualized in the PASCAL VOC dataset.
In a similar way, when I try to get the threshold for the BDD dataset, I get 8.860468, which is close to the threshold set by the author. OOD labels are visualized in the BDD dataset.

#13 explains the method for image classification, and in the case of object detection, I understand that the threshold value is obtained with "metric_utils.py".
Is this understanding correct?

**Comment by d12306** [comment]
hi @hori-13 , thanks for the interest in our codebase! 

the way to get the threshold is similar to the image classification for object detection task. 

could you change 10 in this line https://github.com/deeplearning-wisc/vos/blob/25eec0dd1af06bcabccc4b20e8f338bf5de909bb/detection/inference/inference_core.py#L131 to 20?
as this means you relabel the ood objects to a different label other than the 20 classes in pascal voc. 

feel free to dive into the details of the visualization code if this change does not produce the ood label

**Comment by hori-13** [comment]
Thank you.
After changing the number of classes pointed out, I was able to display the OOD label.
Thank you for your kind reply.
