### ISSUE TITLE
Loss function question in code

### ISSUE THREAD

**Issue by hori-13** [deeplearning-wisc/vos#38]
Thank you for your kind reply.
Where in the code is the uncertainty loss for the object detection task calculated?
Also, where in the code is the final loss, which consists of the classification, bounding box regression, and uncertainty loss in Equation 7 of the paper, calculated?

**Comment by d12306** [comment]
hi, please see the loss summary here. https://github.com/deeplearning-wisc/vos/blob/25eec0dd1af06bcabccc4b20e8f338bf5de909bb/detection/modeling/roihead_gmm.py#L905
