### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by shuangw98** [deeplearning-wisc/vos#40]
Thanks for your great work! 
I have some questions about the evaluation metrics. In my understanding, the two metrics (FPR95 & AUROC) are independent of the localization accuracies. Even most of the predictions on OOD images are false positive, the metrics may still be high.
Is there something wrong with my understanding? Thanks.

**Comment by d12306** [comment]
@WuShuang1998 , thanks for your interest!

for object detection networks, we apply the thresholding mechanism to filtering the low-confidence predictions. 
in real-world  applications, practically we usually collect the predictions from the object detectors directly for usage.

But yes, further reducing the false positives in the predictions seem to be more practical.
