### ISSUE TITLE
Question about model evaluation

### ISSUE THREAD

**Issue by MLRadfys** [deeplearning-wisc/vos#42]
Hi and thanks for sharing you work on outlier detection.

Iam wondering how exactly you determine the reduction in False positives between a vanilla model and a VOS-trained model?
As far as I have understood, the numbers obtained after running apply_net.py are not used (False positives, Ignorance Score, Bier Score ...) and the FPR95 metric is used for the ID/OOD classifier?

Is there are way to obtain the FP with and without VOS?

Thanks in advance,

M

**Comment by d12306** [comment]
Hi, @MLRadfys , yes, the numbers  obtained after running apply_net.py are not used. It is obtained by the legacy code in https://github.com/asharakeh/probdet. 

 FPR95 metric will be calculated after you run the voc_coco_plot.py

**Comment by MLRadfys** [comment]
Thank you very much for the quick reply!

As far as I can see, the FPR95 metric is computed based on ID data only in the voc_coco_plot.py script. 
In your paper (table 1), you also provide the FPR95 measure for the OOD data (when ID is either VOC or Berkeley). 

It would be very interesting to know how you derived these numbers.

In addition, I noticed that some papers use FPR95, while others use FPR90 for OOD detection. Do you have any "feeling" for the difference between the two measures?

Thanks again for taking the time to answer my questions :-)

Kind regards

M

**Comment by d12306** [comment]
hi, @MLRadfys , please check https://github.com/deeplearning-wisc/vos/blob/main/metric_utils.py for how we implement it. FPR95 is the standard metric in ood detection literature. you can also use fpr90, and compare with baselines. that sounds interesting to me!

**Comment by MLRadfys** [comment]
Thanks again for your reply!

The reason why I asked if one could use FPR90 is that I can't get any good results on a model trained on my own dataset (I use the coco validation dataset as OOD though).
The determined threshold is not able to catch many OOD samples.
Nevertheless, when I change the recall level to 90%, the results look much better. Unfortunately I don't have any good intuition for the FPR@k recall measure.

/M
