### ISSUE TITLE
question about about the paper

### ISSUE THREAD

**Issue by BigBuffa1o** [deeplearning-wisc/vos#47]
How do you detect a OOD object and give it a bounding box, instead of trade it as background,since it haven't been annotated in training data anyway?Thank you

**Comment by d12306** [comment]
Hi, @BigBuffa1o , we only care about OOD detection on the detected objects in this paper. and we do not care about the missing objects. this is also more reasonable in practice. If there is no false prediction, then how can we identify them out?

 The missing OOD objects are an interesting research topic these days. See https://arxiv.org/abs/2108.06753
