### ISSUE TITLE
How to only do testing using pre-trained model

### ISSUE THREAD

**Issue by mcairlangga2** [deeplearning-wisc/vos#48]
Dear Authors,
Sorry for the dumb question since I'm a beginner. I only want to use the pre-trained weight that you already provided for testing. However, I do not know how to load the weights in the model using this detectron2. Could you please show me the step from loading the weight (say VOS on ResNet) and evaluating it on the dataset? (ID: VOC, OOD: OpenImages). Thanks!

**Comment by d12306** [comment]
hi, @mcairlangga2 , please follow the instructions in the readme file. the inference-only command line is already specified.
