### ISSUE TITLE
I cannot find the virtual outliers synthesizing code.

### ISSUE THREAD

**Issue by jinweiisgreat** [deeplearning-wisc/vos#50]
Thank you for your work, but I really want to know how to synthesize these points. Thanks!

**Comment by d12306** [comment]
hi, @jinweiisgreat , it starts from here https://github.com/deeplearning-wisc/vos/blob/a449b03c7d6e120087007f506d949569c845b2ec/detection/modeling/roihead_gmm.py#L840, and a few lines below

**Comment by d12306** [comment]
for classification networks, it starts from here: https://github.com/deeplearning-wisc/vos/blob/a449b03c7d6e120087007f506d949569c845b2ec/classification/CIFAR/train_virtual.py#L228
