### ISSUE TITLE
Can VOS be applied to yolov6 (1-stage detector) rather than 2-stage detector?

### ISSUE THREAD

**Issue by ChangGiMoon** [deeplearning-wisc/vos#51]
Dear authors,
Can VOS be applied to yolov6 (1-stage detector) rather than 2-stage detector?

**Comment by d12306** [comment]
hi @ChangGiMoon , I think it might be feasible for such extension. since the yolo also has a classification head. There are some differences between them as well, such as the training objectives and the meaning of the objects/anchors. You are encouraged to have a try.
