### ISSUE TITLE
VOS inference on single image in object detection

### ISSUE THREAD

**Issue by yonafalinie** [deeplearning-wisc/vos#52]
Hello, that you for the awesome work in OOD detection. May I ask if I can do the inference only on single image for VOS in object detection? Suppose I have a single image for which I want to know the object detected with Faster R-CNN in the image in distribution or out of distribution? 
Do I need to use apply_net.py to to analyze this? 
I had a look on issue #13  but from my reading it seems like it is only for classification? 

Thank you so much and looking forward to your reply

**Comment by yonafalinie** [comment]
I found a quick fix where I just create coco json format with empty annotation for my images (I use 3 images), then register the annotation in setup_datasets.py then I manage to get the inference.  I was wondering if there is a way to do the inference without creating any coco json format?

**Comment by d12306** [comment]
hi, @yonafalinie , you can load the single image before this line,https://github.com/deeplearning-wisc/vos/blob/a449b03c7d6e120087007f506d949569c845b2ec/detection/apply_net.py#L86C1-L86C1 and then collect the inference results.

please also be aware of the possible data augmentation and cropping before you load the image. ideally, it should be consistent to the original codebase.
