### ISSUE TITLE
Utilizing the VOS for small dimension datasets

### ISSUE THREAD

**Issue by kaltinel** [deeplearning-wisc/vos#6]
Hi,

I kindly want to congratulate you on your new paper, `VOS`!
I am very intrigued to use it for my current dataset, which is small in size (total of 1000 datapoints for supervised data) and dimension (1x7 shaped tensors) stored in .txt files.

I have two sources for my supervised dataset (two datasets generated in different days by different people (batch effect)). 
Therefore, the density distribution for the same labels coming from two sources are unfortunately different.
And I do not know where the noise is.

I was trying to overlap their density distribution by scaling one of them to the other, however after seeing your `VOS`, I have an idea of generating data based on their OOD data and use it in training..

Do you think I can utilize your VOS for my goal?
I appreciate your insights!
Thank you!

**Comment by d12306** [comment]
hello, @kaltinel , thanks for the interest in vos, i think if you are targetting at the classification task and the ood generalization task, you can probably try to using vos for data augmentation purpose and see how sampling from the low-density area helps the ood generalization task. I am not sure about the performance but you can try it and see the accuracy.

let me know if you have further questions!
