### ISSUE TITLE
Covariance matrix not PositiveDefinite for larger feature sizes

### ISSUE THREAD

**Issue by jorism1993** [deeplearning-wisc/vos#7]
Hi,

I tried applying the classification example with a different network. To be specific, I tried the Xception network which has a feature size of 2048 (the WideResNet model from your code has a feature size of 128). This introduces an error, raised by PyTorch:

`ValueError: Expected parameter covariance_matrix (Tensor of shape (2048, 2048)) of distribution MultivariateNormal(loc: torch.Size([2048]), covariance_matrix: torch.Size([2048, 2048])) to satisfy the constraint PositiveDefinite(), but found invalid values:...` Interesting enough, this does not happen with the `efficientnet-b5` model (which also has a feature size of 2048). Do you maybe know what is going on?

**Comment by d12306** [comment]
hi, @jorism1993 , thanks for your interest in vos!
could you post the complete log and code? I don't think it is related to the feature dimension here.
Also, the covariance matrix in the code is always positive-definite since it is calculated in the form of <img src="https://render.githubusercontent.com/render/math?math=A^T A">.

**Comment by jorism1993** [comment]
Complete log:
```
{'batch_size': 64, 'calibration': False, 'dataset': 'cifar10', 'decay': 0.0005, 'droprate': 0.3, 'epochs': 100, 'layers': 40, 'learning_rate': 0.1, 'load': '', 'loss_weight': 0.1, 'model': 'xception', 'momentum': 0.9, 'ngpu': 1, 'prefetch': 4, 'sample_from': 10000, 'sample_number': 1000, 'save': './snapshots/baseline', 'select': 1, 'start_epoch': 0, 'test': False, 'test_bs': 200, 'widen_factor': 2}
Files already downloaded and verified
Files already downloaded and verified
Beginning Training

 21%|██▏       | 168/782 [00:20<01:15,  8.10it/s]
Traceback (most recent call last):
  File "/home/joris/Documents/VOS/train_virtual.py", line 336, in <module>
    train(epoch)
  File "/home/joris/Documents/VOS/train_virtual.py", line 230, in train
    new_dis = torch.distributions.multivariate_normal.MultivariateNormal(
  File "/home/joris/.virtualenvs/VOS/lib/python3.8/site-packages/torch/distributions/multivariate_normal.py", line 146, in __init__
    super(MultivariateNormal, self).__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/home/joris/.virtualenvs/VOS/lib/python3.8/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter covariance_matrix (Tensor of shape (2048, 2048)) of distribution MultivariateNormal(loc: torch.Size([2048]), covariance_matrix: torch.Size([2048, 2048])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[ 0.0126,  0.0041, -0.0008,  ...,  0.0072,  0.0063, -0.0031],
        [ 0.0041,  0.0108, -0.0011,  ...,  0.0050,  0.0043, -0.0011],
        [-0.0008, -0.0011,  0.3559,  ..., -0.0020, -0.0023,  0.3560],
        ...,
        [ 0.0072,  0.0050, -0.0020,  ...,  0.0141,  0.0057, -0.0029],
        [ 0.0063,  0.0043, -0.0023,  ...,  0.0057,  0.0106, -0.0026],
        [-0.0031, -0.0011,  0.3560,  ..., -0.0029, -0.0026,  0.3748]],
       device='cuda:0')

Process finished with exit code 1
```

Code: [here](https://drive.google.com/file/d/1Xx7ossVroJIuD-eposCgEzaMmbRd2wZO/view?usp=sharing) or [here](https://we.tl/t-kNcmJbA2WI)
Run with: `python3 train_virtual.py -b 64 --start_epoch 0 --ngpu 1 --sample_number 1000 --model xception`

**Comment by d12306** [comment]
hi, @jorism1993 , I think the problem is that you set the start_epoch to be 0 which leads to a bad quality of the gaussian mixture model estimated. I changed the start_epoch to 2 and the error never occurs.

**Comment by d12306** [comment]
feel free to reopen the issue if you have further questions on it.

**Comment by jorism1993** [comment]
@d12306 Setting the `start_epoch` to `2` does not feel like a solution to this problem. You said yourself that the covariance matrix should always be positive-definite since it is calculated in the form of A^T A 

Have you been able to reproduce my errors?

Furthermore I noticed that increasing the value with which the identity matrix is multiplied also helps with at least postponing this error: (no idea how this impacts performance)
OLD: `temp_precision += (0.0001 * torch.eye(2048, device=features.device))`
NEW: `temp_precision += (0.01 * torch.eye(2048, device=features.device))`
Any idea why this might be?

**Comment by d12306** [comment]
i have not reproduced the exact same error as you, but i got this error 
```
RuntimeError: cholesky_cuda: U(677,677) is zero, singular U
```
i think increase the start_epoch is going to help the estimation of the Gaussian mixture model, which we found will improve the ood detection performance. we highly suggest you don't set the start_epoch to 0. and that will solve this bug.
```
temp_precision += (0.0001 * torch.eye(2048, device=features.device))
```
is used to solve the numerical instability for covariance matrix estimation and the later sampling procedure. I remeber i read it somewhere adding a diagonal matrix will help remove the bug. i am happy to share with you but now i cannot find the post.

you can use this trick (increase from 0.0001 to 0.01) to see the ood detection performance.
